import 'package:flutter/material.dart';

import './pages/fishs.dart';
import './pages/fish.dart';

import './models/fish.dart';

final fishList = [
  Fish(id: "1", name: 'Płoć', description: "Płoć , płotka (Rutilus rutilus) - ryba z rodziny karpiowatych. Ciało kr&oacute;tkie, wysoko wygrzbiecone, bocznie ściśnięte, w wodach ubogich w pokarm bardziej wysmukłe. Głowa kr&oacute;tka, szczęka g&oacute;rna nieco wysunięta przed mały, końcowo położony otw&oacute;r gębowy. Płetwy piersiowe najdłuższymi promieniami sięgają nasad płetw brzusznych. Grzbiet ciemnobrązowy lub szaroczarny z niebieskawym lub zielonkawym połyskiem, boki jasnosrebrzyste, brzuch biały. Płetwa grzbietowa i ogonowa są szare z czerwonawym odcieniem, inne płetwy czerwonawe. Tęcz&oacute;wka oka czerwona. Odżywianie: Małe organizmy zwierzęce oraz rośliny.", image: 'http://images48.fotosik.pl/20/56f66916f8367ddb.jpg'),
  Fish(id: "2", name: 'Leszcz', description: "Leszcz (Abramis brama) - ryba słodkowodna z rodziny karpiowatych. Leszcz jest gatunkiem bytującym w głębokich słodkich wodach stojących, zasobnych w osady mułowe, o czym świadczy jego kształt ciała (wydatny brzuch i grzbiet, co dowodzi dużej zwrotności ryby w płaszczyznach pionowych) i ryjkowaty pyszczek (leszcz żywi się pokarmem zalegającym w mule. Dzięki właściwościom swojego aparatu gębowego jest w stanie zasysać muł, a następnie wypluwać go i wyszukiwać cząstki pokarmu). Żyje w stadach: gromadnie odbywa tarło, zespołowo żeruje, a zimuje w wielkich zgromadzeniach. Stada rzeczne nie są jednak tak liczne jak te jeziorne. Ryba jest gatunkiem ciepłolubnym; ma wysokie wymagania cieplne w czasie rozrodu. Temperatura tarła wynosi 13-18 &deg;C, wylęg zdrowych larw odbywa się w temp. 19-22 &deg;C. Optymalna temperatura żeru to 17-23 &deg;C. W przeciętnie ciepłym roku sezon leszczowy w rzece zaczyna się po tarle, trwa od czerwca do początku września. Kulminacja przypada w lipcu i pierwszej połowie sierpnia. Osiąga przeciętnie 3,5-4 kg wagi i do 70 cm długości. Zdarzają się także osobniki 7 kilogramowe.", image: 'http://images50.fotosik.pl/20/fd449ad0253234d4.jpg'),
  Fish(id: "3", name: 'Krąp', description: "Krąp (Blicca bjoerkna) - ryba z rodziny karpiowatych. Jedyny przedstawiciel rodzaju Blicca, często mylona z leszczem. R&oacute;żni się jednak od niego mniejszą ilością promieni miękkich w płetwach: grzbietowej i odbytowej oraz mniejszą ilością łusek w linii bocznej. Dorasta przeciętnie do 30 cm (maks. 36 cm) i 0,5 kg wagi (maks. 1 kg). Żywi się bezkręgowcami, larwami owad&oacute;w i roślinami. Często uważana za szkodnika. Z tego powodu nie posiada ani wymiaru ani okresu ochronnego.", image: 'http://images43.fotosik.pl/20/30b2e5b844265aae.jpg'),
  Fish(id: "4", name: 'Karp', description: "Karp (Cyprinus carpio) - ryba z rodziny karpiowatych. mocny tuł&oacute;w o płaskiej stronie brzusznej, ubarwienie ciała - ż&oacute;łtobrunatne do ciemnobrunatnego - zależne od odmiany oraz warunk&oacute;w środowiskowych, otw&oacute;r gębowy końcowy z grubymi wargami i czterema wąsikami &ndash; dwa małe, na g&oacute;rnej wardze, i dwa większe, w kącikach pyska, wysuwalne g&oacute;rne szczęki, płetwa grzbietowa pojedyncza, długa, początek przypada w najwyższym punkcie grzbietu przed nasadą płetwy brzusznej, koniec sięga nasady płetwy odbytowej, płetwa ogonowa nieco zaokrąglona, słabo wcięta, kr&oacute;tka płetwa odbytowa kolor mięsa: białe mięso (tłusta ryba), czerwone mięso (chuda ryba),brak żołądka. Odżywia się drobnymi zwierzętami wodnymi, owadami i ślimakami. W czasie żeru wydaje odgłosy przypominające mlaskanie. Bardzo ostrożny i płochliwy. Może żyć ponad 20 lat. Ryba bardzo płodna, na 1 kg masy ciała samicy przypada średnio 100&ndash;200 tys. ziaren ikry. W wodach polskich nie odbywa naturalnego tarła, z powodu zbyt niskiej temperatury wody. Odmiany hodowlane są wyższe, grubsze i bardziej odporne na choroby. Kotlina Oświęcimska jest jednym z gł&oacute;wnych centr&oacute;w hodowli karpia w Polsce.<br /><br /> sazan &ndash; odmiana dzika, ciało pokryte grubą, dobrze osadzoną łuską, tworzącą jednolitą pokrywę, bywa mylony z amurem, <br />lustrzeń, karp kr&oacute;lewski (dawniej karp galicyjski) - odmiana wyhodowana w Polsce, silnie wygrzbiecone ciało oraz rząd dużych łusek wzdłuż linii bocznej i w okolicach głowy, karp pełno łuski, karp bezłuski (golec), <br />karp koi &ndash; ozdobna odmiana w wielu wariantach z efektownym ubarwieniem &ndash; białe, zwykle z plamami pomarańczowymi, czerwonymi lub czarnymi. Często hodowane w ozdobnych zbiornikach przydomowych (stawach, sadzawkach i oczkach ogrodowych).Pochodzi z Japonii, ryba ma zwykle 30-40 cm długości, może dochodzić do 75 cm. Poszczeg&oacute;lne odmiany hodowlane (ponad 100) r&oacute;żnią się zar&oacute;wno ubarwieniem, jak i ułuszczeniem. Przebywa przy dnie, gdzie ryje podłoże i wygrzebuje rośliny. Żywi się gł&oacute;wnie roślinami i glonami, a także drobnymi zwierzętami wodnymi. Jak wszystkie odmiany hodowlane, koi jest wrażliwa na zimną wodę.<br /> Karp zatorski - unikalny gatunek miejscowego pochodzenia. Karp zatorski jest lustrzeniem o ułuszczeniu wieńcowym, strzałkowym lub siodełkowym i ubarwieniu oliwkowo &ndash; niebieskim. ", image: 'http://images32.fotosik.pl/380/960899cdcc2f0bd5.jpg'),
  Fish(id: "5", name: 'Karaś', description: "Karaś (Carassius) &ndash; rodzaj ryb z rodziny karpiowatych. długość: 20-35 cm (wyjątkowo do 40cm), waga: 2-2,5 kg (wyjątkowo do 5 kg), rozmnażanie: jajorodne, ilość jaj: 150 000-300 000, czas inkubacji: 3-7 dni, dojrzałość płciowa: 2-3 lat (samiec), 3-4 lat (samica), pożywienie: larwy owad&oacute;w, niewielkie skorupiaki, mięczaki, długość życia: 5-10 lat (w hodowli do 25 lat) Rekordowa długość życia wynosiła 28 lat, zasięg występowania: w rzekach całej Polski i zbiornikach wodnych, z wyjątkiem szybko płynących potok&oacute;w i zbiornik&oacute;w g&oacute;rskich, siedlisko: płytkie, zarastające roślinnością zbiorniki wodne, wypłycone części dużych jezior, małe oraz ciepłe jeziora z bogatą roślinnością wodną.", image: 'http://images32.fotosik.pl/380/2dc416c67e113220.jpg'),
  Fish(id: "6", name: 'Kleń', description: "Kleń (Leuciscus cephalus syn. Squalius cephalus) gatunek słodkowodnej ryby karpiokształtnej z rodziny karpiowatych. Przeciętnie osiąga długość 40-50 cm i 2-3 kg wagi, maksymalnie dorasta do 60cm. Ciało wrzecionowate, lekko bocznie spłaszczone, pokryte dużymi, czarno obrzeżonymi łuskami. Dzięki temu charakterystycznemu ułuszczeniu łatwo go odr&oacute;żnić od jazia i jelca. Szeroki otw&oacute;r gębowy w położeniu końcowym. Płetwa grzbietowa i ogonowa szarozielone, płetwy brzuszne i odbytowa - czerwone. Płetwa odbytowa zaokrąglona. Grzbiet szaro-brązowy z zielonym odcieniem, boki srebrzyste, brzuch jasny. Tęcz&oacute;wka szara.", image: 'http://images48.fotosik.pl/20/4cee93f0699dd8d8.jpg'),
  Fish(id: "7", name: 'Jaź', description: "Jaź (Leuciscus idus) - gatunek słodkowodnej ryby karpiokształtnej z rodziny karpiowatych. Osiąga 40-50(80)cm długości i 2(5)kg wagi. Ciało bocznie spłaszczone, lekko wygrzbiecone, pokryte małymi łuskami. Głowa mała, otw&oacute;r gębowy w położeniu końcowym. Oczy duże. Grzbiet szaroniebueski lub ciemnozielony, boki srebrzyste, brzuch biały. Płetwy grzbietowa, ogonowa i odbytowa są są szare, pozostałe ż&oacute;łtawe lub czerwonawe. Żywi się owadami, mięczakami, skorupiakami a czasem także małymi rybami.", image: 'http://images39.fotosik.pl/20/9e4e8f0b163c4fb4.jpg'),
  Fish(id: "8", name: 'Certa', description: "Certa (Vimba vimba) - ryba anadromiczna z rodziny karpiowatych. Długość do 50 cm (zazwyczaj 30-40 cm). Ciało wydłużone, mocno bocznie spłaszczone, na brzuchu pozbawiony łusek kil, na grzbiecie przed płetwą grzbietową r&oacute;wnież pozbawiony łusek rowek. Otw&oacute;r gębowy miękki o grubych wargach, brzuszny położony w dolnej części wystającego pyska. Płetwa ogonowa głęboko wcięta. Grzbiet szarawoniebieski, boki srebrzyste, brzuch biały, tęcz&oacute;wka szarobrązowa. W okresie tarła grzbiet i boki stają się prawie czarne, a sp&oacute;d ciała pomarańczowy lub ż&oacute;łty.", image: 'http://images32.fotosik.pl/380/18c5d563432665c8.jpg'),
  Fish(id: "9", name: 'Lin', description: "Lin (Tinca tinca) - słodkowodna ryba z rodziny karpiowatych, jedyny przedstawiciel rodzaju Tinca. Ciało lina jest pokryte drobnymi łuskami, mocno osadzonymi w śluzowatej sk&oacute;rze. Płetwy charakterystycznie zaokrąglone. Otw&oacute;r gębowy poziomy. W kącikach znajduje się po jednym kr&oacute;tkim i miękkim wąsiku. Żyje w niezbyt głębokich, mulistych i obficie porośniętych wodach rzek i jezior. Hodowany w gospodarstwach stawowych. Występuje w całej Europie pr&oacute;cz Islandii, p&oacute;łnocnej Szkocji, Skandynawii, Dalmacji, Grecji, Krymu. W Azji spotykany na Syberii. Spotykany w wodach słonawych, np. w zlewisku Bałtyku. Hodowlana odmiana, zwana złotym linem jest w naszym klimacie bardzo popularną rybą ozdobną, często spotykaną w przydomowych oczkach wodnych i stawkach. Osiąga długość 70 cm i wagę 6 kg (Węgry, Rumunia). Żywi się drobnymi zwierzętami dennymi. Aktywniejszy nocą. Zimę spędza zagrzebany w mule. Lin jest także nosicielem bakterii jadu kiełbasianego. Tarło rozpoczyna w połowie czerwca. Samica składa około 300 tys. jaj na 0,5 kg. swej wagi przylepiając je do roślin wodnych. Młode wylęgają się po 3 dniach. Dojrzałość płciową osiągają po 3-4 latach.", image: 'http://images38.fotosik.pl/20/d4afbb4fd4504be5.jpg'),
  Fish(id: "10", name: 'Okoń', description: "Okoń (Perca) &ndash; rodzaj drapieżnych ryb słodkowodnych zaliczany do okoniokształtnych. p&oacute;łnocnoamerykański Perca flavescens'' (Mitchill, 1814), azjatycki Perca schrenkii Kessler, 1874, europejski Perca fluviatilis L., 1758 &ndash; jeden z najpospolitszych w Polsce gatunk&oacute;w, występujący w większości zbiornik&oacute;w słodkowodnych oraz w przybrzeżnych wodach Bałtyku. Dorasta do 50 cm długości (średnio 25-30 cm), waga do 3 kg (najczęściej nie przekracza 1 kg). Ma duży pysk, kt&oacute;ry zdolny jest do dużego rozwarcia. Łuski koloru srebrnego, drobne i głęboko umiejscowione. Ich charakterystyczne ząbkowane krawędzie nadają rybie szorstkość w dotyku. Ma dużą, dwudzielną płetwę grzbietową; przednia jej część, większa, rozpięta jest na ostrych, kolczastych promieniach twardych. Płetwy brzuszne, odbytowa i ogonowa są barwy pomarańczowej, na brzegach krwistoczerwone. Część grzbietowa mocno wysklepionego ciała jest ciemnoturkusowa. Rozpoczynają się na niej, schodząc w kierunku jaśniejszych bok&oacute;w, charakterystyczne ciemne, poprzeczne pręgi w liczbie 5-9. Okonie żyją w stadach, przy dnie, blisko krzak&oacute;w, kamieni i innych kryj&oacute;wek. Największe ławice tworzą małe okonie, większe sztuki pływają zwykle w mniej liczebnych grupach. Tarło odbywa się w kwietniu-maju, przy brzegach. Samica składa 15 000 - 20 000 jaj; ikra skupiona jest w długie wstęgi. Niedoświadczeni wędkarze mogą go pomylić z sandaczem, jednak ten drugi wyr&oacute;żnia się smuklejszą budową, większymi gabarytami i inną paszczą. Ze względu na dużą płodność i żarłoczność często jest uważany za szkodnika. Odławiany z uwagi na smaczne mięso. Inne nazwy regionalne: okłoń, garbus (z racji wygrzbiecenia u większych osobnik&oacute;w), kostyrz. Okoń został zaaklimatyzowany w Australii, gdzie cieszy się dużą popularnością.", image: 'http://images27.fotosik.pl/284/6e14c8efe80fe2cb.jpg'),
  Fish(id: "11", name: 'Sandacz', description: "Sandacz (Sander lucioperca) &ndash; gatunek drapieżnych, słodkowodnych ryb z rodziny okoniowatych. Jest najbardziej atrakcyjnym gatunkiem pod względem wędkarskim, cenowym oraz walor&oacute;w smakowych mięsa. W okresie młodocianym odżywia się w stawach drobnymi zwierzętami bezkręgowymi. Na drapieżny tryb życia przechodzi w r&oacute;żnym czasie, decyduje o tym ilość i jakość pokarmu, w stawach o gęstej obsadzie chowany w monokulturze już po 2-3 tygodniach. W drugim roku życia odżywia się wyłącznie drobnymi rybami. Dojrzałość płciową osiągają samce w wieku 3 lat, samice 4 lat. Płodność względna ok. 200-250 tys. ziaren ikry, drobnej, kleistej. Sandacz składa ikrę jednorazowo w gniazdach o średnicy 50x60 cm, na r&oacute;żnym substracie: piachu, roślinności wodnej, trawie, korzeniach włośnikowych, jałowcu, świerku, trawie morskiej, korzeniach traw. Ciało krępe, wydłużone, szczupakowate, z szarobrązowym lub szarozielonym grzbietem, boki srebrzystozielone pokryte ciemnymi, poprzecznymi smugami. Na płetwie grzbietowej i ogonowej ciemne, regularnie rozmieszczone plamki. Pysk długi, spiczasty z szerokim otworem gębowym. Dorasta do 1,3 m, osiągając do 23 kg. Przeciętna masa odławianych sandaczy wynosi 3 - 5 kg. Rekord Polski 15,6 kg.", image: 'http://images37.fotosik.pl/20/c34edd2cabbcebd6.jpg'),
  Fish(id: "12", name: 'Szczupak', description: "Szczupak (Esocidae) - rodzina ryb szczupakokształtnych. Osiąga długość do 1,5 m i masę do około 30 kg. Okazy ponad 15-20 kg są rzadkie. Ciało ich jest spłaszczone, opływowe. Głowa wydłużona, ze zwężającymi się szczękami i bardzo szerokim spłaszczonym pyskiem. Zęby szczupaka na dolnej szczęce są skierowane do środka i bardzo ostre, szczęka g&oacute;rna jest ich pozbawiona. Ponadto liczne zęby występują na kości podniebiennej, kościach międzyszczękowych, lemieszu, kości gnykowej oraz łukach skrzelowych. Łuski są dosyć małe, owalne, mocno osadzone w sk&oacute;rze.Linia boczna dobrze rozwinięta, często poprzerywana, posiada ona dwa lub trzy rozgałęzienia wzdłuż bok&oacute;w. Na głowie znajdują się liczne jamki zmysłowe. Płetwy grzbietowa i odbytowa są przesunięte mocno do tyłu i położone blisko siebie. Ubarwienie zmienne w zależności od warunk&oacute;w środowiska. Młode osobniki są zwykle jasnozielone, brązowawe lub srebrzyste. Ciemne plamy na bokach zlewają się czasami w poprzeczne smugi. Starsze osobniki mają ciemnozielony grzbiet, jaśniejsze nakrapiane ż&oacute;łtymi plamami boki i biały brzuch. Płetwy parzyste są czerwonawe i jasne, na nieparzystych występują ciemne poprzeczne paski. W dobrych warunkach rośnie bardzo szybko. Jest świetnie przystosowany do życia wodnego drapieżnika, normalnie nie jest aktywnym myśliwym, choć zalicza się do najbardziej drapieżnych ryb. Czyha w ukryciu między roślinami wodnymi i czeka na przepływającą zdobycz. Większe osobniki mogą aktywnie gonić ławice ryb (na przykład śledzi) w strefie pelagicznej dużych jezior albo Bałtyku. Szczupak wybiera ryby często występujące w jego ekosystemie i dostatecznie duże, żeby były warte wysiłku&rdquo;. Wśr&oacute;d szczupak&oacute;w częstym zjawiskiem jest kanibalizm.", image: 'http://images40.fotosik.pl/20/9e72d9c32bf6ec9d.jpg'),
  Fish(id: "13", name: 'Węgorz', description: "Węgorz europejski (Anguilla anguilla) &ndash; ryba z rodziny węgorzowatych (Anguillidae), rzędu węgorzokształtnych (Anguilliformes). Ubarwienie najczęściej ciemne, czasem niemal całkowicie czarne, sp&oacute;d srebrzysty lub ż&oacute;łtawobiaławy. Sk&oacute;ra węgorza pokryta jest grubą warstwą śluzu. Łuski są drobne, elipsoidalne, głęboko osadzone. Nie ma płetw brzusznych. Osiąga od 100 do 150 cm długości. Samce są mniejsze od samic i osiągają długość od 50 do 70 cm (tzw. sznur&oacute;wki). Największy węgorz złowiony dotąd w Polsce ważył 6,43 kg (w Anglii 5,5 kg). Żywi się gł&oacute;wnie fauną denną (bezkręgowce) i drobnymi rybami, potrafi połykać zdobycz stosunkowo dużych rozmiar&oacute;w. Jest zawziętym prześladowcą rak&oacute;w podczas ", image: 'http://images29.fotosik.pl/284/97d2c7f4cfc9d690.jpg'),
  Fish(id: "14", name: 'Wzdręga', description: "Wzdręga (Scardinius erythrophthalmus syn. Notemigonus crysoleucas roseus) L.1758 - ryba z rodziny karpiowatych (Cyprinidae), często mylona z płocią od kt&oacute;rej jest bardziej jaskrawo ubarwiona i ciało ma silniej spłaszczone. Wzdręga bywa r&oacute;wnież nazywana krasnopi&oacute;rką. Osiąga długość 25-30(40) cm i wagę do 1 kg. Ciało bocznie spłaszczone. Otw&oacute;r gębowy mały przedni, skierowany skośnie ku g&oacute;rze. Pomiędzy płetwami piersiowymi a odbytową występuje ostry, pokryty łuskami kil. Płetwa grzbietowa przesunięta do tyłu (jej przednia krawędź znajduje się na wysokości tylnej krawędzi płetw piersiowych. Grzbiet jest niebieskozielony, boki srebrzystobiałe z wyraźnym złotawym odcieniem. płetwy grzbietowa i piersiowe szare z czerwonawym odcieniem, pozostałe płetwy jaskrawoczerwone. Tęcz&oacute;wka oka ż&oacute;łta lub pomarańczowa.", image: 'http://images39.fotosik.pl/20/b7058ca497347f5a.gif'),
  Fish(id: "15", name: 'Sum', description: "Sum (Silurus glanis) - duża ryba z rodziny sumowatych, żyjąca w Polsce. Największa ryba słodkowodna Europy. Osiąga długość ponad 2 m i wagę ponad 100 kg (maksymalnie 5 m i wagę 306 kg)[1]. Ciało długie pozbawione łusek, głowa duża, otw&oacute;r gębowy duży silnie uzębiony. Nad g&oacute;rną szczęką znajdują się dwa długie, a pod dolną cztery kr&oacute;tkie wąsy. Płetwa grzbietowa jest silnie zredukowana, posiada tylko 3-5 promieni, natomiast płetwa odbytowa jest bardzo długa i sięga prawie do zaokrąglonej płetwy ogonowej. Ogon bardzo długi, stanowi 3/5 długości ciała. Oczy małe, nozdrza zakończone kr&oacute;tkimi mięsistymi rurkami. Ubarwienie zależy od środowiska. Grzbiet jest ciemny lub prawie czarny, czasem z zielonkawym, niebieskawym lub brązowawym odcieniem. Boki ciemnoż&oacute;łtawobiałe z wyraźnym szarobrązowym marmurkowym wzorem, brzuch szarobiały z ciemnymi nieregularnymi plamami. Czasami występują czerwonookie osobniki albinotyczne. Dożywa ponad 30 lat. Wybitny drapieżnik. Poluje na ryby r&oacute;żnych gatunk&oacute;w, jest kanibalem. Wbrew pozorom większość zdobyczy to niewielkie rybki o długości kilkunastu centymetr&oacute;w.", image: 'http://images31.fotosik.pl/381/d251bfa20054d93d.gif'),
  Fish(id: "16", name: 'Miętus', description: "Miętus (Lota lota) - jedyna słodkowodna ryba z rodziny dorszowatych. Długość przeciętnie około 60 cm (maksymalnie 120 cm), masa do 34 kg. Ciało ma kształt walcowaty, w dotyku bardzo miękkie. Charakterystyczną cechą jest pojedynczy wąs na środku brody oraz ustawienie płetw brzusznych przed piersiowymi. Głowa jest mocno spłaszczona, przypomina wyglądem głowę żaby. Miętus jest rybą zimnolubną. Tarło odbywa w zimie, w wodzie o temperaturze 2-4 &deg;C. W zależności od masy może złożyć od 10 tys. do 3 mln jaj. Żarłoczna zimą - pożywia się owadami, mniejszymi rybami, rakami i żabami.", image: 'http://images33.fotosik.pl/386/7618c3d787683afe.jpg'),
  Fish(id: "17", name: 'Boleń', description: "Boleń (Aspius aspius) - ryba z rodziny karpiowatych. Boleń bywa r&oacute;wnież nazywany rapem lub rapą. Długie, wyciągnięte, bocznie nieco spłaszczone ciało. Głowa spiczasta, oczy małe. Szeroki, końcowo położony otw&oacute;r gębowy. Nieco wysunięta szczęka dolna ma na końcu garbikowate zgrubienie, chowające się we wgłębieniu szczęki g&oacute;rnej. Łuski małe, 64-76 wzdłuż linii bocznej. W płetwie grzbietowej 10-11 promieni, w odbytowej 15-18. Krawędź płetwy odbytowej sierpowato wcięta. Zęby gardłowe dwurzędowe. Ubarwienie grzbietu oliwkowozielone z niebieskawym połyskiem. Boki jaśniejsze, ż&oacute;łto lśniące. Strona brzuszna srebrzyście biała. Płetwy piersiowe, brzuszne oraz odbytowa są czerwonawe. Długość 50-75 cm, maksymalnie 120 cm (ciężar do 12 kg).", image: 'http://images50.fotosik.pl/20/4dd474ac775ad56d.jpg'),
  Fish(id: "18", name: 'Brzana', description: "Brzana (Barbus barbus) - gatunek słodkowodnej ryby z rodziny karpiowatych. Ciało długie, niskie i walcowate. Otw&oacute;r gębowy dolny wysuwany zaopatrzony w dwie pary wąsik&oacute;w. oczy skierowane nieco ku g&oacute;rze. Płetwa ogonowa głęboko wcięta. Ostatni promień płetwy grzbietowej jest twardy i gruby, na tylnej krawędzi ząbkowany. Grzbiet oliwkowozielony lub ciemnoszary, boki jaśniejsze, brzuch biały. Płetwy grzbietowa i ogonowa szare z ciemniejszym obrzeżeniem, pozostałe płetwy czerwonawe. Osiąga przeciętnie około 70 cm, maksymalnie 120 cm długości i 12 kg wagi. Rekord Polski wynosi 85 cm (2003). Gł&oacute;wnym pokarmem są larwy owad&oacute;w wodnych (much&oacute;wki, chruściki, widelnice, jętki) oraz kiełże, mięczaki i skąposzczety, rzadziej małe ryby.", image: 'http://images41.fotosik.pl/20/5c285232d6bea904.jpg'),
  Fish(id: "19", name: 'Lipień', description: "Lipień (Thymallus thymallus) - słodkowodna, zimnolubna ryba z rodziny łososiowatych Dorasta do długości 50 cm. Ciało ma lekko spłaszczone i małą głowę. Otw&oacute;r gębowy niewielki, przedni, z drobnymi zębami, szczęka g&oacute;rna nieco dłuższa od dolnej. Łuski są duże, mocno osadzone w sk&oacute;rze. Młode osobniki są srebrzysto-jasnozielone z niebieskawymi plamami na bokach. Osobniki starsze mają grzbiet szarozielony, zielonkawe boki i biały brzuch. Na bokach podłużne ciemne smugi odpowiadające poszczeg&oacute;lnym rzędom łusek. Płetwy nieparzyste mają bladofioletowy odcień, płetwa grzbietowa jest długa, wysoka i ozdobiona kilkoma rzędami czerwonych i czarnych plamek. Całe ciało ma metaliczny połysk. Płetwy grzbietowa, odbytowa, i piersiowe większe u samc&oacute;w niż u samic. Żyje przeciętnie 4-5 lat, maksymalnie 10. Jego liczebność i rozmieszczenie ze względu na kr&oacute;tkowieczność są zmienne.", image: 'http://images31.fotosik.pl/381/feaa0ab274b1a713.gif'),
  Fish(id: "20", name: 'Troć jeziorowa', description: "Troć jeziorowa (Salmo trutta lacustris L.) &mdash; ryba z rodziny łososiowatych należąca do gatunku Salmo trutta. Osiąga bardzo r&oacute;żne rozmiary w zależności od miejsca występowania. W niekt&oacute;rych jeziorach dorasta do 5 kg, w innych osiąga 30 kg i 1,5 m długości. Szczeg&oacute;lnie duże rozmiary osiąga w Alpach. Ubarwienie jest srebrne z licznymi czarnymi plamkami na bokach, grzbiecie i głowie..", image: 'http://images33.fotosik.pl/386/81984fde72d0cacd.jpg'),
  Fish(id: "21", name: 'Troć wędrowna', description: "Troć wędrowna (Salmo trutta trutta) &mdash; anadromiczna ryba wędrowna, należąca do gatunku Salmo trutta. Osiąga długość ponad 1 m, 30 kg wagi. W por&oacute;wnaniu z łososiem ma bardziej krępe ciało i większą głowę. Grzbiet jest szarawy lub brązowawy, boki jaśniejsze a brzuch srebrzysty. Głowa boki i grzbiet są pokryte licznymi czarnymi plamkami kt&oacute;re w czasie tarła mają ż&oacute;łtą obw&oacute;dkę. Płetwa tłuszczowa czerwono obrzeżona. W okresie tarła u samc&oacute;w pojawiają się czerwone plamki na bokach i przybierają one charakterystyczną miedzianobrązową barwę ciała. Młode osobniki maja ciemne poprzeczne prążkowanie i czerwone plamki na ciele.", image: 'http://images43.fotosik.pl/20/8b9d5e20cdef1e82.jpg'),
  Fish(id: "22", name: 'Pstrąg potokowy', description: "Pstrąg potokowy (Salmo trutta fario) - ryba z rodziny łososiowatych (Salmonidae). W Polsce osiąga maksymalnie ok. 80 cm i 5 kg. Kształt torpedowaty - ułatwiający życie w wartkim prądzie rzeki. Ubarwienie bardzo zmienne - zależne od miejsca przebywania. Na ciele liczne czarne i czerwone kropki. Brzuch ż&oacute;łtobiały lub ż&oacute;łty. Płetwa tłuszczowa jasna, ciemnoobrzeżona. Młode osobniki mają duże, wyraźne niebieskoszare plamy na bokach. Dorosłe samce mają często hakowato zagiętą ku g&oacute;rze szczękę dolną i dłuższą głowę niż samice..", image: 'http://images33.fotosik.pl/386/8ef166072a9095bd.jpg'),
  Fish(id: "23", name: 'Pstrąg tęczowy', description: "Pstrąg tęczowy (Oncorhynchus mykiss), pot. tęczak - ryba z rodziny łososiowatych, należąca do rodzaju łososi pacyficznych. Ubarwienie jest zależne od wieku i miejsca przebywania. Najczęściej srebrne boki, niebieskoszary lub zielonoszary grzbiet, r&oacute;żowa wstęga wzdłuż linii bocznej (kt&oacute;rej zawdzięcza swoją nazwę) oraz zawsze czarne plamki na bokach i płetwach. Długość: do 145 cm, zazwyczaj 40-60 cm, Waga: do 23 kg, zwykle 4-5, Dojrzałość płciowa: w 2 roku życia, Ikra: 500 do 3000 sztuk stosunkowo dużej ikry Długość życia: w środowisku naturalnym najwyżej 7 lat, w Kalifornii widziano jednak 11-letnie pstrągi.", image: 'http://images46.fotosik.pl/20/bb136109959716c4.jpg'),
  Fish(id: "24", name: 'Pstrąg źródlany', description: "Pstrąg źródlany (Salvelinus fontinalis) pot. źr&oacute;dlak - ryba z rodziny łososiowatych, należąca do rodzaju Salvelinus obejmującego golce i palie. Osiąga zwykle 20-35 (50) cm i wagę do 3 kg. Ciało wydłużone, lekko bocznie ścieśnione. Otw&oacute;r gębowy sięga za tylną krawędź oka. Grzbiet zielonobrązowy. Na zielonoż&oacute;łtych bokach charakterystyczny marmurkowy wzorek oraz zielone, czerwone i ż&oacute;łte plamki. Płetwy ogonowa i grzbietowa są jasnooliwkowe, ta pierwsza nakrapiana czarnymi plamkami. Płetwy piersiowe, brzuszne i odbytowa są pomarańczowe, ich białe krawędzie mają czarną obw&oacute;dkę. Samce w okresie rozrodu mają jaskrawopomarańczowe podbrzusze. Drobne łuski cykloidalne.", image: 'http://images26.fotosik.pl/285/b41e9850adbca67b.jpg'),
];

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (BuildContext context) => FishsPage(fishList),
        '/fish': (BuildContext context) => FishPage(fishList[0]),
      },
      onGenerateRoute: (RouteSettings settings) {
        final List<String> pathElements = settings.name.split('/');
        if (pathElements[0] != '') {
          return null;
        }
        if (pathElements[1] == 'fish') {
          final String fishId = pathElements[2];
          final Fish fish =
            fishList.firstWhere((Fish fish) {
              return fish.id == fishId;
            });
          return MaterialPageRoute < bool > (
            builder: (BuildContext context) => FishPage(fish),
          );
        }
        return null;
      },
    );
  }
}
